# api base url
URL: "http://www.baidu.com"
BASE_URL: "http://172.17.3.34"

# api server db
sql:
  sql_server: 172.17.3.34
  sql_port: 3306
  sql_name: sensenets
  sql_user: root
  sql_password: Sensenets123

# log config
log:
  file_name: test.log
  backup: 5
  console_level: DEBUG
  file_level: DEBUG
  pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

# socket
ip: 127.0.0.1
port: 8080

# email config
email:
  server: 'smtp.exmail.qq.com:465'
  sender: 'zhangjiukun@sensenets.com'
  password: 'iPkywPhbdFan7fnh'
  receiver: 'zhangjiukun@sensenets.com;850871592@qq.com'
  title: '冒烟测试报告'

pvg_server_67:
  ip: 10.0.100.12
  port: 2100
  user: admin
  password: admin
  type: PVG67
  real_count: 150

pvg_server_10:
  ip: 10.0.100.36
  port: 2015
  user: admin
  password: 123456
  type: PVG10
  real_count: 132372

rtsp_server_1:
  real_count: 1
  type: rtsp
  url: rtsp://10.0.10.200:8557/H264

---

pvg_server_67:
  name: 172.17.2.34
  ipAddress: 172.17.2.34
  version: PVG6_7
  port: 2100
  description: ""
  ext: "{\"uid\":\"admin\",\"pwd\":\"admin\"}"
  real_count: 20

